openapi: 3.0.1
info:
  title: logic-rax
  description: Azure Logic App.
  version: '1.0'
servers:
  - url: https://apim-demo-dib.azure-api.net/logic-app
paths:
  /When_a_HTTP_request_is_received/paths/invoke:
    post:
      summary: When_a_HTTP_request_is_received-invoke
      description: Trigger a run of the logic app.
      operationId: When_a_HTTP_request_is_received-invoke
      requestBody:
        description: The request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-When_a_HTTP_request_is_received'
            example:
              input: string
      responses:
        '200':
          description: The Logic App Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/When_a_HTTP_request_is_receivedPathsInvokePost200ApplicationJsonResponse'
        '500':
          description: The Logic App Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/When_a_HTTP_request_is_receivedPathsInvokePost500ApplicationJsonResponse'
components:
  schemas:
    request-When_a_HTTP_request_is_received:
      required:
        - input
      type: object
      properties:
        input:
          type: string
      example:
        input: string
    When_a_HTTP_request_is_receivedPathsInvokePost200ApplicationJsonResponse:
      type: object
    When_a_HTTP_request_is_receivedPathsInvokePost500ApplicationJsonResponse:
      type: object
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]